issue-952: card carousel
moonshine-software/moonshine pull request #1019
Opened 2024-06-03 18:35 UTC by djnew

https://github.com/moonshine-software/moonshine/issues/952 Слайдер в компоненте Card
```php 
Card::make(
                    title: fake()->sentence(3),
                    thumbnail: [
                        "http://via.placeholder.com/300x200",
                        "http://via.placeholder.com/300x200",
                        "http://via.placeholder.com/300x200",
                    ],
                    url: fn() => 'https://cutcode.dev',
                    values: ['ID' => 1, 'Author' => fake()->name()],
                    subtitle: date('d.m.Y')
                )
```
![image](https://github.com/moonshine-software/moonshine/assets/886244/5daa6f1b-bf2b-4146-826b-83eb23345e25)
![image](https://github.com/moonshine-software/moonshine/assets/886244/d7cbcf2b-e69f-40f3-a34f-7517f87ffef4)
![image](https://github.com/moonshine-software/moonshine/assets/886244/f517324d-f603-4e5f-95df-b3ea7f260222)
![image](https://github.com/moonshine-software/moonshine/assets/886244/ddb20ac8-d843-4f12-94c7-5714c341cb9c)

```php 
Card::make(
                    title: fake()->sentence(3),
                    thumbnail: "http://via.placeholder.com/300x200",
                    url: fn() => 'https://cutcode.dev',
                    values: ['ID' => 1, 'Author' => fake()->name()],
                    subtitle: date('d.m.Y')
                )
```

![image](https://github.com/moonshine-software/moonshine/assets/886244/0ed5054a-c69c-4488-a618-b28f9e705aad)

2024-06-04 06:12 UTC, DissNik commented
Для полного счастья осталось CardsBuilder поправить )
Еще визуально мне кажется нужно добавить отступ у кнопок  prev / next, а сами иконки чуть уменьшить

2024-06-04 06:56 UTC, DissNik requested changes

2024-06-04 06:56 UTC, DissNik commented on resources/css/components/cards.css
> +        @apply absolute top-1/2 w-full;
режим `overlay`

```suggestion
      &-navigation{
        @apply absolute top-1/2 w-full z-10;
```

![Снимок экрана 2024-06-04 в 11 38 26](https://github.com/moonshine-software/moonshine/assets/12373059/7d96d9ad-f227-4b29-8954-352b7f914177)

навигация слайдов под тестовым блоком

2024-06-04 06:56 UTC, DissNik commented on resources/css/components/cards.css
> +        @apply absolute bottom-0 w-full text-center bg-white bg-opacity-50 dark:bg-opacity-50 dark:bg-dark-600;
```suggestion
        @apply absolute bottom-0 w-full text-center bg-white bg-opacity-50 dark:bg-opacity-50 dark:bg-dark-600 text-[.75rem] z-10;
```

![Снимок экрана 2024-06-04 в 11 52 41](https://github.com/moonshine-software/moonshine/assets/12373059/30114a9c-54ea-44e7-a048-1058d86e20a5)

стили просто для примера

2024-06-04 07:18 UTC, djnew commented on resources/css/components/cards.css
> +        @apply absolute top-1/2 w-full;
![image](https://github.com/moonshine-software/moonshine/assets/886244/516c5dec-d461-4a50-94cc-dededb38daae)
добавил

2024-06-04 07:18 UTC, djnew commented on resources/css/components/cards.css
> +        @apply absolute bottom-0 w-full text-center bg-white bg-opacity-50 dark:bg-opacity-50 dark:bg-dark-600;
![image](https://github.com/moonshine-software/moonshine/assets/886244/5244eee5-600f-4229-ad98-f522cf24580c)
Добавил

2024-06-04 07:53 UTC, lee-to requested changes

2024-06-04 07:53 UTC, lee-to commented on resources/views/components/card.blade.php
> +            @if(gettype($thumbnail) === 'string')
используй is_* он быстрее

2024-06-04 07:53 UTC, lee-to commented on resources/views/components/card.blade.php
> +                <div class="card-photo-carousel" x-data='carousel(
хорошо бы карусель сделать отдельным компонентом (если это возможно конечно) чтобы юзать и в других блоках

2024-06-04 07:56 UTC, lee-to commented on resources/views/components/card.blade.php
> +    'thumbnail',
по дефолту давай оставим строку

2024-06-04 08:36 UTC, djnew commented on resources/views/components/card.blade.php
> +                <div class="card-photo-carousel" x-data='carousel(
попробую вытащить

2024-06-06 18:03 UTC, lee-to commented on public/assets/app.js
Кстати старайся исключить скомпилированные билды из пр

2024-06-12 07:47 UTC, djnew commented on public/assets/app.js
ок постараюсь

2024-06-12 07:49 UTC, djnew commented
Вытащил карусель в компонент
![image](https://github.com/moonshine-software/moonshine/assets/886244/dbabbae1-19a9-48fc-87e3-0bcb2064faed)
`            Block::make([
                Grid::make([
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x200",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x260",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x200",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: "http://via.placeholder.com/300x200",
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3)
                ]),
            ]),
            LineBreak::make(),
            Block::make([
                Grid::make([
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x200",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(6),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: "http://via.placeholder.com/300x200",
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(6)
                ]),
            ]),
            LineBreak::make(),
            Block::make([
                Grid::make([
                    Column::make([
                        Carousel::make(
                            title: fake()->sentence(3),
                            thumbnail: [
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                            ],
                            album: true
                        )
                    ])->columnSpan(4),
                    Column::make([
                        Carousel::make(
                            title: fake()->sentence(3),
                            thumbnail: "http://via.placeholder.com/200x300",
                            album: true
                        )
                    ])->columnSpan(4),
                    Column::make([
                        Carousel::make(
                            title: fake()->sentence(3),
                            thumbnail: [
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                            ],
                            album: true
                        )
                    ])->columnSpan(4),
                ])
            ]),`

докинул альбомную ориентацию в компонент карусели, определения карусель или картинка выкинул в класс

2024-06-12 08:46 UTC, djnew commented
примеры после последней переделки
```php
Block::make([
                Grid::make([
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnails: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x200",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnails: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x260",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnails: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x200",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnail: "http://via.placeholder.com/300x200",
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y')
                        )
                    ])->columnSpan(3)
                ]),
            ]),
            LineBreak::make(),
            Block::make([
                Grid::make([
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnails: [
                                "http://via.placeholder.com/1280x720",
                                "http://via.placeholder.com/1024x768",
                                "http://via.placeholder.com/300x200",
                            ],
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y'),
                        )->overlay()
                    ])->columnSpan(6),
                    Column::make([
                        Card::make(
                            title: fake()->sentence(3),
                            thumbnails:
                            "http://via.placeholder.com/1024x768",
                            url: fn () => 'https://cutcode.dev',
                            values: ['ID' => 1, 'Author' => fake()->name()],
                            subtitle: date('d.m.Y'),
                        )
                    ])->columnSpan(6)
                ]),
            ]),
            LineBreak::make(),
            Block::make([
                Grid::make([
                    Column::make([
                        Carousel::make(
                            title: fake()->sentence(3),
                            items: [
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                            ],
                            album: true
                        )
                    ])->columnSpan(4),
                    Column::make([
                        Carousel::make(
                            title: fake()->sentence(3),
                            items: "http://via.placeholder.com/200x300",
                            album: true
                        )
                    ])->columnSpan(4),
                    Column::make([
                        Carousel::make(
                            title: fake()->sentence(3),
                            items: [
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                                "http://via.placeholder.com/200x300",
                            ],
                            album: true
                        )
                    ])->columnSpan(4),
                ])
            ]),
```

2024-06-12 11:05 UTC, djnew commented
Примеры использования, скрыл кнопку назад на первом слайде, скрыл кнопку вперед на последнем слайде, переименовал параметры компонента чтобы выглядело логично
```php
           \MoonShine\Components\Card::make(
                title: fake()->sentence(3),
            )
                ->thumbnails(['/images/image_2.jpg','/images/image_1.jpg']);


            \MoonShine\Components\Carousel::make(
                alt: fake()->sentence(3),
            )
            ->items(['/images/image_2.jpg','/images/image_1.jpg']);
```

2024-06-14 07:36 UTC, lee-to approved these changes

2024-06-14 07:36 UTC, merged