Query tags and filters
moonshine-software/moonshine pull request #1060
Opened 2024-06-19 15:49 UTC by DissNik

- корректное отображение тега по умолчанию в асинк режиме
- сохранение активного тега и сортировки в асинк режиме
- корретное число активных фильтров в асинк режими

2024-06-19 19:20 UTC, lee-to requested changes
в целом помоему супер, все логично

2024-06-19 19:20 UTC, lee-to commented on resources/js/alpine/asyncLink.js
> +    const element = document.querySelector('.query-tag-default')
у нас есть activeClass может и defaultClass сделаем?

2024-06-19 19:20 UTC, lee-to commented on resources/js/alpine/formBuilder.js
> +    let filledFields = new Set()
может вынесем в метод чтобы легче читалось?

2024-06-19 19:20 UTC, lee-to commented on src/Forms/FiltersForm.php
> -                    'disable-query-tags',
А почему убрали это событие?

2024-06-20 02:28 UTC, DissNik commented on src/Forms/FiltersForm.php
> -                    'disable-query-tags',
Нам не нужно сбрасывать теги, фильтр применяется с активным тегом

2024-06-20 02:38 UTC, DissNik commented on resources/js/alpine/asyncLink.js
> +    const element = document.querySelector('.query-tag-default')
.query-tag-default по стилям никакой нагрузки не несет и нужен для нахождения элемента, так же как и .query-tag-button, поэтому не вижу большого смысла выносить его в параметры

через activeClass мы передаем класс для стилизации активного пункта и его же можно использовать для поиска активного пункта, поэтому я удалил дублирование с .active-query-tag

2024-06-24 07:37 UTC, merged