feat: add config option export.format
moonshine-software/moonshine pull request #1080
Opened 2024-06-28 16:49 UTC by JeRabix

в конфиг муншайна добавил параметр export -> format

чтобы можно было формат экспорта по умолчанию задать xlsx

2024-06-28 19:26 UTC, lee-to commented
Не вижу ничего плохого

2024-06-29 04:12 UTC, DissNik requested changes

2024-06-29 04:12 UTC, DissNik commented on src/Traits/Resource/ResourceModelActions.php
> +        if (config('moonshine.export.format') !== 'xlsx') {
мне кажется так лучше
```suggestion
        if (config('moonshine.export.format') === 'csv') {
```

2024-06-29 04:14 UTC, DissNik requested changes

2024-06-29 04:14 UTC, DissNik commented on config/moonshine.php
> +        'format' => 'csv', // xlsx or csv
У нас по дефолту сейчас xlsx, думаю не стоит его менять на csv

2024-06-29 04:50 UTC, JeRabix commented
Как раз таки по умолчанию сейчас csv, поэтому я этот ПР и сделал)

И чтобы не сломать логику у всех пользователей сейчас, стоит оставить все таки csv.

2024-06-29 06:52 UTC, DissNik commented
да... спорный момент

> Как раз таки по умолчанию сейчас csv, поэтому я этот ПР и сделал)
> 
> И чтобы не сломать логику у всех пользователей сейчас, стоит оставить все таки csv.

точно. я был уверен! что у нас xlsx по умолчанию, надо тогда доку поправить

2024-06-29 18:26 UTC, lee-to commented
Кстати судя по отсутствующему фидбеку то что по дефолту сейчас csv то возможно не так и часто нужно менять, поэтому предлагаю концепт через статический метод, выглядить будет вот так

```php
public static function exportCsv(): void
{
    self::$exportCsv = true;
}

public function export(): ?Handler
{
    return ExportHandler::make(__('moonshine::ui.export'))->when(
        self::$exportCsv,
        static fn(ExportHandler $handler) => $handler->csv()
    );
}
```

Далее кому надо просто потом в провайдере сделают

```php
ModelResource::exportCsv();
```

2024-07-01 09:15 UTC, shevelev-anatoliy commented
По своему опыту скажу, что на Windows постоянные проблемы с отображением кириллицы в csv файлах, открываемых в Excel. Отображаются кракозябры. Чтобы это решить приходится проделывать ряд манипуляций с файлом. Поэтому я в своих проектах никогда не использую экспорт в csv, и не только в муншайне.

2024-07-01 09:16 UTC, shevelev-anatoliy commented
> Кстати судя по отсутствующему фидбеку то что по дефолту сейчас csv то возможно не так и часто нужно менять


По своему опыту скажу, что на Windows постоянные проблемы с отображением кириллицы в csv файлах, открываемых в Excel. Отображаются кракозябры. Чтобы это решить приходится проделывать ряд манипуляций с файлом. Поэтому я в своих проектах никогда не использую экспорт в csv, и не только в муншайне.

2024-07-01 12:15 UTC, closed without merging