Condition for show/hide methods
moonshine-software/moonshine pull request #11
Opened 2022-07-23 17:05 UTC by Opekunov

Add condition for methods:
- showOnIndex
- hideOnIndex
- showOnForm
- hideOnForm
- showOnExport
- hideOnExport

2022-07-24 06:38 UTC, lee-to requested changes

2022-07-24 06:38 UTC, lee-to commented on src/Fields/Field.php
> +        return $default;
Добавь blank line

2022-07-24 06:38 UTC, lee-to commented on src/Fields/Field.php
> +            return filter_var($conditionResult, FILTER_VALIDATE_BOOLEAN);
blank line

2022-07-24 06:38 UTC, lee-to commented on src/Fields/Field.php
> +        return $default;
blank line

2022-07-24 06:38 UTC, lee-to commented on src/Fields/Field.php
> +            return filter_var($conditionResult, FILTER_VALIDATE_BOOLEAN);
не стоит приводить к булеан типу, у нас указан возвращаемый тип, пусть лучше юзер получит ошибку и увидит что делает что то не так а у тебя в итоге получится inline return
return is_null($condition) 
? $default 
: (is_callable($condition) ? $condition() : $condition);

2022-07-24 14:26 UTC, Opekunov commented
- create trait
- include into attributes methods

2022-07-25 09:17 UTC, lee-to requested changes

2022-07-25 09:17 UTC, lee-to commented on src/Traits/Fields/WithHtmlAttributes.php
> +    use HasBooleanCondition;
вот этот момент мне не нравится

2022-07-25 13:58 UTC, lee-to requested changes

2022-07-25 13:58 UTC, lee-to commented on src/Utilities/Helpers.php
> +final class Helpers
Давай переименуем в ConditionHelpers

2022-07-26 11:04 UTC, merged