feat(export): added the ability to export with confirmation
moonshine-software/moonshine pull request #1101
Opened 2024-07-12 15:27 UTC by carma100

Для экспорта добавил возможность экспорта по подтверждению. Не стал расширять до возможности управления `title`, `content`, `button` и `fields` - на мой взгляд в этом нет необходимости на кнопке **Экспорта**.

![image](https://github.com/user-attachments/assets/72b35bf0-75c6-4e3b-8e71-8814bf369403)
![image](https://github.com/user-attachments/assets/fc3c6117-eb0c-422d-b831-02068807f49f)

В одном из проектов подтверждение - это необходимость, т.к. есть таблица с 5 миллионами записей и необдуманные клики по **Экспорту** сожрут много ресурсов и времени.

2024-07-12 15:49 UTC, DissNik requested changes

2024-07-12 15:49 UTC, DissNik commented on src/Buttons/ExportButton.php
> +        if ($export->withConfirm()) {
у вас тут объект ExportHandler

2024-07-12 15:57 UTC, lee-to commented
Идея возникла просто сделать декоратор modifyExport/Import/FilterButton по типу тех которые мы уже делали для кнопок ресурса, это даст возможность ставить свои конфермы но а сахар с вашим конфермом в целом можно тоже оставить

2024-07-13 15:53 UTC, carma100 commented
Спасибо за обратную связь, посмотрю аналоги, переделаю.

2024-07-15 20:33 UTC, carma100 commented
@DissNik изменил обращение к объекту ExportHandler, в итоге понял что проще и правильнее будет в уже свой ExportHandler добавить `protected bool $withConfirm = true;`. А вот с декораторами что-то туплю

2024-07-16 02:13 UTC, DissNik commented on src/Handlers/ExportHandler.php
> -    public function withConfirm(): static
Мне кажется зря вы это метод убрали. Если у меня нет потребности создавать свой ExportHandler, то я бы мог добавить confirm

```php
use MoonShine\Handlers\ExportHandler;

// ...
 
public function export(): ExportHandler
{
    return ExportHandler::make('Export')
        ->withConfirm();
}
```

2024-07-16 02:45 UTC, DissNik commented
Вот тут реализация декораторов кнопок ресурса, нужно что-то подобное

https://github.com/moonshine-software/moonshine/blob/d31c091701495fad6cf91b545173221603296dce/src/Traits/Resource/ResourceWithButtons.php#L95

2024-07-16 08:47 UTC, carma100 commented on src/Handlers/ExportHandler.php
> -    public function withConfirm(): static
Справедливое замечания, сахар вернул.

2024-07-16 08:49 UTC, carma100 commented
@DissNik 
Добавил декоратор для кнопки EditButton. Может быть стоит отрефакторить трейт `ResourceWithButtons`: `modifyCreateButton`, `modifyEditButton`, `modifyExportButton` и т.д. имеют одну и ту же логику, заменить на 1 функцию:
```php
protected function modifyButton(ActionButton $button): ActionButton
{
    return $button;
}
```

сделать в рамках текущего ПР или отдельный ПР сделать?

2024-07-16 08:57 UTC, lee-to commented
> @DissNik Добавил декоратор для кнопки EditButton. Может быть стоит отрефакторить трейт `ResourceWithButtons`: `modifyCreateButton`, `modifyEditButton`, `modifyExportButton` и т.д. имеют одну и ту же логику, заменить на 1 функцию:
> 
> ```
> protected function modifyButton(ActionButton $button): ActionButton
> {
>     return $button;
> }
> ```
> 
> сделать в рамках текущего ПР или отдельный ПР сделать?

Они имеют разные названия с одинаковой логикой что ты мог потом в ресурсе менять конкретную кнопку а не все

2024-07-16 08:58 UTC, lee-to commented
Давай сразу в этом пр добавим враппер для фильтра и импорта

2024-07-16 09:10 UTC, carma100 commented
Добавил враппер для фильтра и импорта.

2024-07-16 10:19 UTC, lee-to requested changes

2024-07-16 10:19 UTC, lee-to commented on src/Traits/Resource/ResourceWithButtons.php
> +        return $this->modifyEditButton(
У тебя здесь Edit вместо Export тем самым твой декоратор никогда не будет вызван

2024-07-16 10:19 UTC, lee-to commented on src/Traits/Resource/ResourceWithButtons.php
> +        return $this->modifyEditButton(
И тут тоже самое, я так понимаю ты не понял вообще суть этих методов

2024-07-16 10:19 UTC, lee-to commented on src/Traits/Resource/ResourceWithButtons.php
> +        return $this->modifyEditButton(
ну и соответственно и тут

2024-07-16 10:22 UTC, carma100 commented on src/Traits/Resource/ResourceWithButtons.php
> +        return $this->modifyEditButton(
это мой косяк, суть работы я понял

2024-07-16 10:29 UTC, lee-to requested changes

2024-07-16 10:29 UTC, lee-to commented on src/Handlers/ExportHandler.php
> +    public function getWithConfirm(): bool
методы проверки на булеан принято называть с префиксом is/has
Давай переименуем в isWithConfirm?

2024-07-16 18:33 UTC, lee-to requested changes

2024-07-16 18:33 UTC, lee-to commented on src/Traits/Resource/ResourceWithButtons.php
> +    public function getFiltersButton(): ActionButton
Вы просто добавили метод который нигде не вызывается. Его надо на IndexPage вызвать

2024-07-16 19:58 UTC, carma100 commented on src/Traits/Resource/ResourceWithButtons.php
> +    public function getFiltersButton(): ActionButton
Понял, по итогу вы были правы, что я ни хрена не понял... И да, скорее всего вы правы были в группе, что проще самому что-то вам поправить, чем столько раз ревьювить код. Прошу понять и простить

2024-07-16 20:07 UTC, lee-to commented on src/Traits/Resource/ResourceWithButtons.php
> +    public function getFiltersButton(): ActionButton
Вы не правильно поняли мои слова в группе, за вашу активность и пр, спасибо, мне не сложно направить вас на правильный путь, тем более что в этом пр это была моя инициатива добавить эти методы

2024-07-16 20:42 UTC, carma100 commented
Обновил PR, сахар работает, кнопки на индексной работают.

2024-07-17 06:08 UTC, lee-to commented
> Обновил PR, сахар работает, кнопки на индексной работают.

Молодец! Не упускай руки а то я в чате бываю тем еще токсиком) И проверяй то что ты делаешь, в слепую всегда возникают проблемы

2024-07-17 12:26 UTC, DissNik approved these changes

2024-07-17 12:36 UTC, DissNik commented
Отличный pr получился. Теперь можно кастомизировать и эти кнопки.

Просьба отредактировать описание и, если есть желание, добавить в документацию

2024-07-17 13:22 UTC, carma100 commented
Описание поправил, документацию обновлю по возможности.

2024-07-17 18:47 UTC, merged