Tabs content through slots
moonshine-software/moonshine pull request #1219
Opened 2024-08-29 18:52 UTC by MadZee-M

Компонент "tabs", добавлена возможность создавать "content" через слоты.

Применение:

Используем префикс "content-" в название слота.

```
<x-moonshine::tabs :tabs="[
    'general' => 'Таб 1',
    'tokens' => 'Таб 2',
    'others' => 'Таб 3',
]">
    <x-slot name="content-general">
        Таб 1 content
    </x-slot>

    <x-slot name="content-tokens">
        Таб 2 content
    </x-slot>

    <x-slot name="content-others">
        Таб 3 content
    </x-slot>
</x-moonshine::tabs>
```

2024-08-30 07:15 UTC, lee-to commented
Интересно но есть сразу проблемы в пр серьезные
1) тут логика из другого пр по copy (такого быть не должно)
2) много логики в блейде

2024-09-01 08:44 UTC, lee-to requested changes
ну и обязательно нужно убрать код из другого пр или этот пр будет закрыт

2024-09-01 08:44 UTC, lee-to commented on resources/views/components/tabs.blade.php
> +        if (! $contents) {
Проверку лучше сделать contents === []

2024-09-01 08:44 UTC, lee-to commented on resources/views/components/tabs.blade.php
> +                ->filter(fn($contentSlot, $name) => array_key_exists($name, $tabs))
зачем нам префикс content- там же нет других слотов, только эти и __default (__default надо просто отфильтровать)

2024-09-01 08:44 UTC, lee-to commented on resources/views/components/tabs.blade.php
> +                    {{ $tabContent instanceof \Illuminate\View\ComponentSlot ? $tabContent->attributes  : '' }}
Предлагаю пока без атрибутов так как эта часть выглядит особенно ужасно

2024-09-01 16:38 UTC, MadZee-M commented on resources/views/components/tabs.blade.php
> +                ->filter(fn($contentSlot, $name) => array_key_exists($name, $tabs))
Все слоты можно вызвать просто как переменные "$tab_1". В $__data лежать все переданные пропсы и слоты.
Если у него будет один из табов будет называться "tabs" и он назовет один из слотов ` <x-slot name="tabs"></x-slot>`, то будет ошибка. Потому что слоты приоритетнее пропсов. Одним словом, нельзя будет использовать названии пропсов для названии "вкладок".

Поэтому было решено использовать префикс, чтобы сделать полностью уникальным переданные tabs

2024-09-01 16:50 UTC, MadZee-M commented
Создал без другого пр
https://github.com/moonshine-software/moonshine/pull/1232

2024-09-01 16:50 UTC, closed without merging