Add slug field
moonshine-software/moonshine pull request #138
Opened 2023-03-30 09:17 UTC by SiTiSem

2023-03-30 16:18 UTC, lee-to commented
Есть идея! Довести поля до ума - добавить метод unique и если он true то в save добавлять проверку уникальности через while скажем чтобы генерировать уникальный slug. что скажешь? или я могу принять pr и сам доделать

2023-03-31 10:55 UTC, alexvenga commented
Вообще со слагом надо аккуратнее очень быть))))
Рекомендую юзать https://github.com/spatie/laravel-sluggable и простое поле Text)))
Потому как по SEO, в идеале он не должен меняться, допустим при изменении имени статьи - чтобы ссылки ведущие на страницу не менялись (на других сайтах)
Да и вообще много чего со слагом тонкого)

2023-03-31 12:08 UTC, DissNik commented
Я раньше делал поле которое при редактировании было заблокировано и чтоб его отредактировать надо было нажать кнопку, чтоб не было соблазнов лишних правок, но иногда надо изменить слаг

2023-04-01 04:38 UTC, SiTiSem commented
> Есть идея! Довести поля до ума - добавить метод unique и если он true то в save добавлять проверку уникальности через while скажем чтобы генерировать уникальный slug. что скажешь? или я могу принять pr и сам доделать
Вообще делал аналог данного типа поля, like as nova. Т.е. алгоритм был таков, что slug генерируется только если данное поле пустое. Если добавить параметр unique, то идея интересная, но тут вопрос, проверять только при пустом поле (т.е. только при генерации), или даже при ручном вводе в данном поле? Если второй вариант, то будет уже более сложное ветвление if...else, необходимо ли?




> Я раньше делал поле которое при редактировании было заблокировано и чтоб его отредактировать надо было нажать кнопку, чтоб не было соблазнов лишних правок, но иногда надо изменить слаг
Можно сделать и так, в nova в общем так и реализовано.

2023-04-01 06:12 UTC, lee-to commented
> > Есть идея! Довести поля до ума - добавить метод unique и если он true то в save добавлять проверку уникальности через while скажем чтобы генерировать уникальный slug. что скажешь? или я могу принять pr и сам доделать
> 
> 
> 
> Вообще делал аналог данного типа поля, like as nova. Т.е. алгоритм был таков, что slug генерируется только если данное поле пустое. Если добавить параметр unique, то идея интересная, но тут вопрос, проверять только при пустом поле (т.е. только при генерации), или даже при ручном вводе в данном поле? Если второй вариант, то будет уже более сложное ветвление if...else, необходимо ли?
> 
> 
> 
> 
> 
> 
> 
> 
> 
> > Я раньше делал поле которое при редактировании было заблокировано и чтоб его отредактировать надо было нажать кнопку, чтоб не было соблазнов лишних правок, но иногда надо изменить слаг
> 
> 
> 
> Можно сделать и так, в nova в общем так и реализовано.

И загляни в пакет spatie sluggable там супер все просто по генерации уникальности

2023-04-01 20:35 UTC, lee-to requested changes

2023-04-01 20:35 UTC, lee-to commented on src/Fields/Slug.php
> +        if (! $this->canSave) {
в версии 1.5 эта проверка не нужна, проверка есть в ресурсе, тут надо убрать этот if

2023-04-01 20:35 UTC, lee-to commented on src/Fields/Slug.php
> +        if ($this->unique)
нужен метод isUnique а свойсвто сделать protected

2023-04-01 20:35 UTC, lee-to commented on src/Fields/Slug.php
> +        $item->{$this->field()} = $this->requestValue() !== false ? $this->requestValue() : $this->generateSlug($item->{$this->from});
Слишком длинная строка, сделать перенос перед ? и :

2023-04-01 20:35 UTC, lee-to commented on src/Fields/Slug.php
> +        $item->{$this->field()} = $this->requestValue() !== false ? $this->requestValue() : $this->generateSlug($item->{$this->from});
from protected и метод геттер для получения from

2023-04-01 20:35 UTC, lee-to commented on src/Fields/Slug.php
> +        return !DB::table($item->getTable())->whereNot('id', $item->id)->where($this->field(), $slug)->first();
Не всегда у нас id бывают и другие названия, сделать $item->getKey() и $item->getKeyName() для получения ключа

2023-04-01 20:35 UTC, lee-to commented on src/Fields/Slug.php
> +        return !DB::table($item->getTable())->whereNot('id', $item->id)->where($this->field(), $slug)->first();
ну и слишком длинная строка сделать переносы после методов

2023-04-04 07:24 UTC, lee-to requested changes

2023-04-04 07:24 UTC, lee-to commented on tests/Fields/SlugFieldTest.php
> +class SlagFieldTest extends TestCase
Slag надо переименовать в Slug

2023-04-05 09:49 UTC, lee-to requested changes

2023-04-05 09:49 UTC, lee-to commented on src/Fields/Slug.php
> +namespace App\MoonShine\Fields;
Если ты добавляешь поле в сам муншайн то namespace должен быть исходя из psr-4 и самого муншайна - Leeto\MoonShine\Fields я сразу не заметил но это грубейшая ошибка

2023-04-05 15:06 UTC, SiTiSem commented on src/Fields/Slug.php
> +namespace App\MoonShine\Fields;
Да, точно, серьезная ошибка, невнимательность при копировании из тестового проекта.

2023-04-05 15:23 UTC, merged