Decoration test cases and phpDoc
moonshine-software/moonshine pull request #17
Opened 2022-07-28 20:24 UTC by seralexs

-phpDoc blocks for some Field methods
-phpDoc blocks for Decorations
-test cases for Decorations

2022-07-28 20:38 UTC, lee-to requested changes

2022-07-28 20:38 UTC, lee-to commented on src/Decorations/Decoration.php
> +     *                      $fields Array of fields will be displayed in tab
Не все декорации имеют табы, это опциональный аргумент, здесь логика поля если требуются для декорации

2022-07-28 20:38 UTC, lee-to commented on src/Fields/Field.php
> +     *
забыл про $condition

2022-07-29 20:00 UTC, seralexs commented on src/Fields/Field.php
> +     *
точно, спасибо, я этот коммит добавил еще неделю назад, по-этому когда подтягивал последние изменения забыл изменить phpDoc

2022-07-30 09:26 UTC, lee-to requested changes

2022-07-30 09:26 UTC, lee-to commented on tests/Decorations/DecorationTest.php
> +        $decoration = Decoration::make('Label', [
Благодаря тебе я увидел что Decoration не абстрактный! От него работать нельзя, он служит оболочкой для декораций Tab, Heading поэтому тесты с инициализией экземплеяра Decoration нужно убрать и оставить только для tab, heading
Обновись с последнего коммита я там сделал их абстрактными

2022-07-30 13:59 UTC, lee-to approved these changes

2022-07-30 14:00 UTC, merged