BelongTo->onlySelect
moonshine-software/moonshine pull request #189
Opened 2023-04-13 16:07 UTC by alexvenga

2023-04-13 19:44 UTC, lee-to requested changes
В целом основная проблема на мой взгляд в концепции основного метода onlySelected он подходит для belongstomany а тут скорее asyncValues

Сложный вопрос но важный так как пахнет будущим депрекейтедом либо для метода onlySelected либо для придуманного нового, надо хорошенько продумать, либо пока не поздно переименовать первоначальный либо добавить сахарный сюда который будет ссылаться на onlySelected

2023-04-13 19:44 UTC, lee-to commented on src/Http/Controllers/SearchController.php
> -        if ($field instanceof BelongsToMany && $type === class_basename($field)) {
Слишком много условий. Нужно добавить интерфейс скажем SearchableField, реализовать его у этих полей и проверять здесь на интерфейс

2023-04-13 19:44 UTC, lee-to commented on src/Http/Controllers/SearchController.php
>      public function relations(string $type)
Это еще я забыл но раз уж мы здесь собрались то давай добавим : JsonResponse

2023-04-13 19:44 UTC, lee-to commented on src/Http/Controllers/SearchController.php
>              $request = request('query');
Давай переменную вынесем за условие и сразу ее и будем проверять на пустоту а то дважды обращаемся к реквесту выглядит не очень

2023-04-13 19:44 UTC, lee-to commented on resources/views/fields/select.blade.php
> +        :fetchRoute="(method_exists($element, 'isOnlySelected') && $element->isOnlySelected()) ?
давай лучше asyncRoute

2023-04-13 19:44 UTC, lee-to commented on resources/views/fields/select.blade.php
> +                    'query' => '',
Я так понял ты передаешь здесь пустой query а потом достраиваешь в app.js но если не знать блейд и смотреть на app.js то выглядит как странная магия, давай не передавать здесь query но в js делать  + query=

p.s не критично но можно подумать и вынести этот роут в трейт поля

2023-04-13 19:44 UTC, lee-to commented on resources/views/components/form/select.blade.php
> +        'x-data' => $fetchRoute ? 'select(\''.$fetchRoute.'\')' : 'select',
без экранирования вот так не пашет `'.$fetchRoute.'` ? и почему не x-data => select('$fetchroite ?? ''')

2023-04-13 19:44 UTC, lee-to commented on resources/views/components/form/select.blade.php
> +    'fetchRoute'=>''
ну тоже переименовать и добавить пробелов

2023-04-13 19:44 UTC, lee-to commented on resources/js/app.js
> +    Alpine.data('select', (fetchRoute = '') => ({
ну и здесь мне кажется лучше будет asyncUrl если на языке блейда мы понимаем роуты то тут уже лучше изолирвоанно

2023-04-13 19:44 UTC, lee-to commented on resources/js/app.js
> +        setChoicesFromFetchApi(url) {
fromUrl можно просто

2023-04-13 19:44 UTC, lee-to commented on resources/js/app.js
> +                  }).then((jsondata) => {
просто json выглядит приятнее)

2023-04-14 12:58 UTC, alexvenga commented on resources/views/components/form/select.blade.php
> +        'x-data' => $fetchRoute ? 'select(\''.$fetchRoute.'\')' : 'select',
без экранирование не пашет - это же строка

2023-04-14 16:44 UTC, merged