fix(change-log): Log actions if requester is MoonshineUser only
moonshine-software/moonshine pull request #303
Opened 2023-05-23 21:32 UTC by Jampire

MoonShine имеет свою систему авторизации. Это приводит к тому, что пользователь может быть одновременно авторизован и на основном сайте, и в админке (под разными учетными данными). В тоже время MoonShine позволяет логировать действия администратора путем подключения трейта `HasMoonShineChangeLog` к той модели, изменения которой нужно логировать. Если пользователь авторизован под двумя учётками и отредактирует логируемую запись  как обычный пользователь, то сработает трейт и запишет изменения в лог как будто редактирование выполнил администратор. Данный фикс позволяет избежать этой проблемы путём проверки кем был инициирован запрос: логирование сработает только если запрос был инициирован администратором.

2023-05-24 07:32 UTC, lee-to commented
Issue отличный но решения пока нет
1) У нас гибкая система аутентификации и можно менять guard и model и в итоге MoonShineUser может и не существовать в системе аутентификации, а мы привязываемся к конкретной модели нарушая все
2) Проблема действительно есть но заход не с той стороны. Давайте разберем алгорит - есть changelog который пишет историю изменений админа в рамках муншайн, зная это мы должны придерживаться правила что changelog нужно писать только в рамках http реквеста (добавить проверку исключащающую консольные изменения) а также нужно проверять что реквест идет именно из роутов муншайн, тем самым зная что запрос в админке и аутентифицирован guard из конфига то все будет работать правильно

Что касается конкретной привязки к моделе, эта информация больше для вашего дальнейшего погружения - MoonShineAuth::model() мы получим модель из текущего guard который выбран для админ панели

2023-05-24 10:42 UTC, Jampire commented
Изменил на проверку `auth.moonshine`, т.к. согласно `MoonShine::resolveResourcesRoutes()` данный middleware будет присутствовать всегда. 
Проверять дополнительно на консоль считаю лишним, т.к. обе эти проверки исключают консольные команды.
Метод `isMoonShineRequest()` можно перенести по желанию в другой класс. Я же добавил его в `MoonShine`.

2023-05-24 10:48 UTC, lee-to requested changes

2023-05-24 10:48 UTC, lee-to commented on src/MoonShine.php
> +    public static function isMoonShineRequest(): bool
Хороший метод, но нужно обязательно его покрыть тестом и напрашивается мысль - логически это все реквесты через муншайн но страница логина исключает мидлвар Authenticate и получается выдаст false что не логично

2023-05-24 11:06 UTC, Jampire commented on src/MoonShine.php
> +    public static function isMoonShineRequest(): bool
Я думал про тест. Но я быстро пробежался по существующим тестам и не нашел там ни одного интеграционного теста (либо я не заметил). А это именно интеграционный тест. Т.е. нужно сперва подготовить фикстуры и стабы для внешнего мини-приложения, который будет обслуживать муншайн. Создание подобной мини-системы не скоуп данного PR и создать её должен разработчик, знающий нюансы и архитектуру муншайн получше, чем я. А этот PR можно заморозить пока это мини-приложение не будет создано.
Я не считаю страницу логина нарушением логики, т.к. в любых системах подобные страницы стоят перед системами, которые они защищают. А значит, с точки зрения middleware, они являются внешними по отношению к системе. Реквест считается внутренним только если он прошел этот барьер.

2023-05-24 11:41 UTC, lee-to commented on src/MoonShine.php
> +    public static function isMoonShineRequest(): bool
У нас есть фича тесты, есть fixtures с билдерами ресурсов, тестовые модели и миграции

2023-05-25 10:57 UTC, Jampire commented
Добавлены тесты.

2023-05-25 13:34 UTC, lee-to requested changes

2023-05-25 13:34 UTC, lee-to commented on tests/Unit/MoonShineTest.php
> +it('recognizes internal request as MoonShine request', function () {
Отправляем реквест, давай лучше перенесем в feature тесты

2023-05-25 13:34 UTC, lee-to commented on tests/Feature/NonMoonShineTest.php
Странное название у теста) Давай лучше сделаем фича тесты changelog и там будет метод по тесту вне муншайн

2023-05-25 13:34 UTC, lee-to commented on tests/Feature/Http/Controllers/CrudControllerTest.php
Опять таки crud и так переполнен, лучше создать фича тесты по changelog и там успешные, не успешные и вне муншайн тесты

2023-05-25 16:11 UTC, Jampire commented on tests/Unit/MoonShineTest.php
> +it('recognizes internal request as MoonShine request', function () {
Тут на вкус и цвет. Feature-тесты же определяются не наличием/отсутствием запроса, а тем, что и как именно тестируется. Фича-тест, как следует из названия, тестирует целиком всю фичу, доступную пользователю. А здесь тестируется метод сам по себе в отрыве от какого-либо контекста. Реквест тут нужен только для того, чтобы метод отработал сам по себе. Можно извратиться и мокнуть сам запрос, но считаю этот перебором конкретно тут.

2023-05-25 16:14 UTC, Jampire commented on tests/Feature/NonMoonShineTest.php
Также на вкус и цвет. Можно и так, но тогда возникает вопрос: почему в фича тестах муншайн находится запрос, не относящийся к муншайн. Смотря с какой стороны подходить к такому фича-тесту.

2023-05-25 16:26 UTC, Jampire commented on tests/Feature/Http/Controllers/CrudControllerTest.php
Вынести все эти тесты в один файл `changelog` будет не совсем корректно. С одной стороны, запросы вне/внутри муншайн никакого отношения к функциональности `changelog` не имеют. С другой стороны, я придерживаюсь мнения, что фича тест должен в одном месте показать всё, что делает фича. Т.к. существует методика быстрого обучения новых разработчиков, которая гласит, что достаточно прочитать тесты, чтобы понять функционал. Если тесты, описывающие одну фичу, будут раскиданы по разным файлам, то общая картина будет складываться очень долго. К тому же, конкретно в данном случае, будет почти полное дублирование `stored/updated` теста.

2023-05-25 16:30 UTC, Jampire commented on tests/Feature/Http/Controllers/CrudControllerTest.php
Даже если вынести в отдельный файл тест на `stored/updated` в исходном файле необходимо сделать какую-либо пометку, что тестируется не весь функционал фичи. Например, начать тест с блокировки событий: `Event::fake()`.

2023-05-26 11:09 UTC, Jampire commented
Изменено согласно пожеланиям.

2023-05-26 11:58 UTC, lee-to commented on tests/Feature/Http/Controllers/CrudControllerTest.php
> +    Event::fake();
можно думаю в beforeEach добавить, у нас внутренних событий кроме changelog в целом и нет

2023-05-26 12:53 UTC, Jampire commented on tests/Feature/Http/Controllers/CrudControllerTest.php
> +    Event::fake();
- они могут появится потом;
- `fake()` намекает стороннему разработчику, что данная фича генерирует события. Если расставить их на каждом тесте, может сложиться ложное впечатление, что каждая фича генерит событие.

2023-05-27 13:24 UTC, merged