feat: Сanceling the default sorting in LineChart
moonshine-software/moonshine pull request #389
Opened 2023-07-15 07:29 UTC by khlystou

Добавил нвый метод в LineChart: withoutSortKeys()
Метод отменяет дефолтную сортировку в графике.

2023-07-15 11:43 UTC, lee-to commented
Тесты не проходят

2023-07-16 07:36 UTC, DissNik requested changes

2023-07-16 07:36 UTC, DissNik commented on src/Metrics/LineChartMetric.php
> +            ->when(! $this->isWithoutSortKeys, fn ($items) => $items->sortKeys())
$this->isWithoutSortKeys()

2023-07-16 07:36 UTC, DissNik commented on src/Metrics/LineChartMetric.php
> +        return $this->withoutSortKeys();
return $this->withoutSortKeys;

2023-07-16 11:34 UTC, khlystou commented on src/Metrics/LineChartMetric.php
> +        return $this->withoutSortKeys();
Поправил

2023-07-16 11:34 UTC, khlystou commented on src/Metrics/LineChartMetric.php
> +            ->when(! $this->isWithoutSortKeys, fn ($items) => $items->sortKeys())
Поправил

2023-07-16 12:45 UTC, merged