fix(fields): Select group mode
moonshine-software/moonshine pull request #410
Opened 2023-07-28 11:01 UTC by YouMixx

Поле Select имеет возможность принимать значения в виде многоуровневого массива - для построения групп.
Но в этом случае выбранное значение не будет отображено в index/show.
Это происходит по той причине, что в функции indexViewValue возвращается значение взятое из массива по ключу.
А если массив поделен на группы - это значение достать не получится.

Мое решение заключается в том, что я добавил новую функцию smoothedValues и использую её в indexViewValue.
Эта функция сглаживает массив до одного уровня, убирая деление на группы.

Я использовал mapWithKeys вместо того-же flatten, дабы не потерять ключи.

------

Остается одна проблема, которую на мой взгляд не нужно решать. Она заключается в том, если в options передали массив поделенный на группы, но при этом не поставили ключи массиву, пример:

```php
'group1' => [
    'test1', // ключ 0
    'test2', // ключ 1
],
'group2' => [
    'test3', // ключ 0
    'test4', // ключ 1
]
``` 

В этом случае ключи при сглаживании некоторые значения пропадут из-за не уникальный ключей.
Можно дописать функцию options, делая ключи уникальными. Но в этом случае, если ключи были и так уникальными мы их просто собьем.

Не вижу делать доп.проверки на то, уникальные ли уже ключи и если нет - делать уникальными. Это задача пользователя, так-что единственное что я рекомендую, упомянуть в документации к информации про группы, что ключи должны быть уникальными.

2023-07-28 13:08 UTC, lee-to requested changes

2023-07-28 13:08 UTC, lee-to commented on src/Traits/Fields/SelectTrait.php
> +    public function smoothedValues() : array
Давай использовать более привычные наименования unwrappedValues либо flattenValues

2023-07-28 13:08 UTC, lee-to commented on src/Traits/Fields/SelectTrait.php
> +        return collect($this->values())->mapWithKeys(function($item, $i) : array {
переменные вместо $item, $i => $value, $key

2023-07-28 13:08 UTC, lee-to commented on src/Traits/Fields/SelectTrait.php
> +            return is_array($item) ? $item : [$i => $item];
тут лучше использовать стрелочную функцию так как логика в строку
fn($value, $key) => is_array($value) ? $value : [$key => $value];

2023-07-28 13:08 UTC, lee-to commented on src/Fields/Select.php
> +        return (string) ($this->smoothedValues()[$value] ?? '');
в поле Enum тоже надо сделать так в indexViewValue

2023-07-29 09:59 UTC, YouMixx commented
Как сейчас должен отрабатывать Enum? Я вывел его пока-что без каких-либо моих изменений. В Edit все отрабатывает корректно, значение можно выбрать, но в index/show выходил ошибка:
![image](https://github.com/moonshine-software/moonshine/assets/89249508/28cd7c20-bb6f-4cda-8f8a-7b36cbdd97fd)

Мне сейчас в принципе не ясно, как он должен отрабатывать. В БД ставится выбранное значение в виде текста, просто ключ поля. А потом в indexViewValue зачем-то пытается получить значение как из коллекции/объекта ($value->value) - из-за этого и происходит ошибка.

Если заменить это просто на $value ($this->values()[$value]) то отрабатывать будет все корректно (но с multiply скорее всего все равно будет ошибка).

Вообщем, не могу понять, или поле багованное или я что-то делаю не так.

+ какой смысл мне распространять мою логику, сделанную для Select на Enum? На сколько я понимаю - Enum не может делится на группы, т.к. в него просто передается EnumCast.

2023-07-30 17:16 UTC, YouMixx commented on src/Fields/Select.php
> +        return (string) ($this->smoothedValues()[$value] ?? '');
Enum разве можно сделать многоуровневым?

2023-07-31 07:02 UTC, merged