feat: Notification color
moonshine-software/moonshine pull request #414
Opened 2023-07-31 12:14 UTC by aka-lamer

Добавление цветовой схемы для уведомлений.
Добалена возможность менять цвета иконки в уведомлениях.
Доступны 7 цветов.
purple - фиолетовый
pink - розовый
blue - голубой
green - зеленый (по умолчанию)
yellow - желтый
red - красный
gray - серый
`
MoonShineNotification::send(
                    message: 'Errore build',
                    color: 'red'
 );
`

2023-07-31 14:56 UTC, lee-to requested changes

2023-07-31 14:56 UTC, lee-to commented on src/Notifications/MoonShineDatabaseNotification.php
> +        protected string $color
у тебя предыдущий аттрибут имеет дефолтное значение а последующий нет, задавай $color по умолчанию определенный цвет или сделай null

2023-07-31 17:16 UTC, DissNik commented on resources/views/layouts/shared/notifications.blade.php
> +                    <div class="notifications-category badge-{{ $notification->data['color'] ?? 'green' }}">
В темной теме при использовании этих стилей будет темный фон и светлая иконка

2023-08-01 04:56 UTC, aka-lamer commented on resources/views/layouts/shared/notifications.blade.php
> +                    <div class="notifications-category badge-{{ $notification->data['color'] ?? 'green' }}">
https://prnt.sc/dwQGUDuWDSJm
В темной теме иконки выглядят прекрасно.

2023-08-01 04:56 UTC, aka-lamer commented on resources/views/layouts/shared/notifications.blade.php
> +                    <div class="notifications-category badge-{{ $notification->data['color'] ?? 'green' }}">
> В темной теме при использовании этих стилей будет темный фон и светлая иконка

https://prnt.sc/dwQGUDuWDSJm
В темной теме иконки выглядят прекрасно.

2023-08-01 06:18 UTC, lee-to commented
Вы меня не поняли) короче сделайте везде string color = 'green'
Где вы такое видели что идут не обязательные параметры а после обязательный? Взяли и исправили в еще более худшую сторону

2023-08-01 14:29 UTC, merged