2.x
moonshine-software/moonshine pull request #489
Opened 2023-09-25 10:19 UTC by pepperfm

2023-09-26 14:11 UTC, lee-to requested changes

2023-09-26 14:11 UTC, lee-to commented on resources/views/components/link.blade.php
> +@aware(['type'])
Давай просто в props

2023-09-26 14:11 UTC, lee-to commented on src/ActionButtons/ActionButton.php
>              : $this->url;
У тебя возможен null

2023-09-26 14:11 UTC, lee-to commented on src/Traits/Fields/WithLink.php
> +        string $type = 'primary'
Давай тут не будем использовать

2023-09-27 12:31 UTC, pepperfm commented on src/ActionButtons/ActionButton.php
>              : $this->url;
возвращаемый тип метода `url()` определён строкой, так что когда я сделал просто `ActionButton::make('test')` (один параметр), получил ошибку

поэтому в конструкторе убрал null и поставил пустую строку: ```php protected Closure|string $url = ''```

2023-09-27 13:41 UTC, merged