feat: dir added when created page
moonshine-software/moonshine pull request #551
Opened 2023-10-17 16:17 UTC by k-rustemuly

Если указать в команде 
```
php artisan moonshine:page Kato/DetailPage
```
Получаем результат
```
DetailPage was created: app/MoonShine/Pages/Kato/DetailPage.php
```
Но этот подход игнорирует --dir опцию

2023-10-18 07:35 UTC, lee-to requested changes

2023-10-18 07:35 UTC, lee-to commented on src/Commands/MakePageCommand.php
> +        if(str($className)->contains('/'))
всегда используй фигурные скобки для конструкций, даже если в 1 строку

2023-10-18 07:35 UTC, lee-to commented on src/Commands/MakePageCommand.php
> +            $dir = str($className)
зачем нам все это? мы можем просто вычислять className через class_basename и удалять его из строки и добавлять так как автор пишет

Var/Var/Var/Class

и тогда не придется игноривовать dir и пусть он тоже добавляется дополнительно при желаниии

И точно не надо фиксировать что обязательно мы должны начинать с Pages

2023-10-20 10:31 UTC, k-rustemuly commented
почему я тесты завалил :(

2023-10-20 11:22 UTC, lee-to commented
> почему я тесты завалил :(

А зачем ты системный параметр extends убираешь и даже не думаешь что он используется

2023-10-20 11:30 UTC, lee-to commented
Имей ввиду что мы добавляем опции не только для удобства взаимодействия с пользователем но и при быстром создании между командами

2023-10-20 12:30 UTC, k-rustemuly commented
отказался от идеи select extends

2023-10-23 08:28 UTC, lee-to commented
Другой апдейт затронул реализацию страниц с директориями но более в упрощенном виде, поэтому этот пр закрываю, если интересно можешь глянуть как в итоге вышло

2023-10-23 08:28 UTC, closed without merging