feat: ValueMetric added short param
moonshine-software/moonshine pull request #649
Opened 2023-11-23 16:27 UTC by k-rustemuly

```
ValueMetric::make('Metric')
      ->short()
      ->value(12000000),
```
Дает результат:
![изображение](https://github.com/moonshine-software/moonshine/assets/16911003/87d94b35-1194-4640-a45c-19383143a47b)

'T', 'B', 'M', 'K'
если больше то добавится еще '+'
![изображение](https://github.com/moonshine-software/moonshine/assets/16911003/3d8b30ed-865c-4053-b9e8-6432097c2a85)

2023-11-23 16:43 UTC, DissNik commented
А чем не устроил valueFormat()?

2023-11-23 20:39 UTC, k-rustemuly commented
> А чем не устроил valueFormat()?

как это сделать?

2023-11-23 20:50 UTC, k-rustemuly commented
это как в инсте количество подписчиков.
если 1000 то 1K 
если 1252 то 1.2K+
и т.д

2023-11-24 04:08 UTC, DissNik commented
```php
$value = 1200000;

ValueMetric::make('Articles')
    ->value($value)
    ->valueFormat(static fn() => \Illuminate\Support\Number::forHumans($value))
```

В вашем случае можно создать свой сервис или хелпер для форматирования строки и использовать его.

Сделал маленькую правку для замыканий #650, можно будет вот так:
```php
ValueMetric::make('Total')
    ->value(45000)
    ->valueFormat(static fn($value) => \Illuminate\Support\Number::currency($value, in: 'EUR'))
```

2023-11-24 04:15 UTC, DissNik requested changes
Ваш случай является частным, поэтому его не стоит добавлять.

2023-11-24 05:28 UTC, closed without merging