Feature/show Детальная страница для элемента модели
moonshine-software/moonshine pull request #72
Opened 2023-01-22 20:13 UTC by volgoden34

Добавил возможность включать в ресурсе детальную страницу элемента. Управление через $activeActions ключем show. Для того, чтобы подключить свой view шаблон для деталки нужно использовать переменную public static string $baseShowView. По умолчанию используется наспех накиданный шаблон moonshine::base.show.

2023-01-23 08:59 UTC, lee-to commented
Не вижу вывод кнопки с отображением ссылки на детальную страницу base/index/shared/items_actions

2023-01-23 09:03 UTC, lee-to commented
Вьюха слишком на скорую руку, даже лейблов нет, нужно доводить до ума, пока что ценности такого функционала не вижу

2023-01-24 07:39 UTC, volgoden34 commented
Добавил вывод кнопки для перехода на деталку. Да, с версткой у меня не очень. Накидал шаблон из элементов с других шаблонов. Постарался чуть улучшить картину добавив лейблы к полям и чуть подшаманил со стилями.

2023-01-24 09:02 UTC, lee-to requested changes

2023-01-24 09:02 UTC, lee-to commented on resources/views/base/index/shared/item_actions.blade.php
> -        <a href="{{ $resource->route("action", $item->getKey(), request()->routeIs('*.query-tag') ? ['index' => $index, 'redirect_back' => 1] : ['index' => $index]) }}"
Зачем удалил это условие?

2023-01-24 09:02 UTC, lee-to commented on resources/views/base/index/shared/item_actions.blade.php
> +@if($resource->can('show', $item) && in_array('show', $resource->getActiveActions()) && !isset($show))
в рамках can у нас проверка на view а не show

2023-01-24 09:02 UTC, lee-to commented on resources/views/base/index/shared/item_actions.blade.php
> -                    @if(request()->routeIs('*.query-tag'))
Зачем удалял?

2023-01-24 09:02 UTC, lee-to commented on resources/views/base/index/shared/item_actions.blade.php
> +@if($resource->can('show', $item) && in_array('show', $resource->getActiveActions()) && !isset($show))
Откуда взялась переменная $show ?

2023-01-24 09:02 UTC, lee-to commented on src/Http/Controllers/MoonShineController.php
> +    public function show($id): mixed
Нужно указать типы которые возвращаются, их не много чтобы ставить mixed

2023-01-24 09:02 UTC, lee-to commented on src/Http/Controllers/MoonShineController.php
> +            'show' => true
зачем нам этот флаг если используем отдельную view

2023-01-24 11:09 UTC, volgoden34 commented on src/Http/Controllers/MoonShineController.php
> +            'show' => true
Через этот флаг добавил проверку на текущую вью, что если отображение на детальной странице, то кнопку - ссылку на детальную показывать не нужно

2023-01-24 13:27 UTC, lee-to commented on src/Http/Controllers/MoonShineController.php
> +            'show' => true
Но проверка стоит в index view в партиале с кнопками, он на show не выводится, нужно убрать эту переменную и проверку в items_actions

2023-02-15 08:15 UTC, closed without merging