feat: add support DbOperator class, change operators for another drivers
moonshine-software/moonshine pull request #798
Opened 2024-02-07 09:53 UTC by JeRabix

# Featues
Добавил супорт класс - DbOperator
для того чтобы можно было операторы для разных драйверов БД подменять.

сразу оператор LIKE поменял везде где использовался функцией этого класса getLikeOperator()

2024-02-07 10:13 UTC, lee-to commented
Мы берем на основе дефолтного коннекта но модель может использовать свой коннект, нужно определять от модели

2024-02-07 10:44 UTC, JeRabix commented
В функцию getLikeOperator добавил $model параметр входной
пытаюсь получить драйвер по модели если передана, потом если передан сам драйвер - берём его - иначе получаем дефолтный драйвер из конфига

2024-02-10 08:39 UTC, lee-to commented
Я предлагаю упростить саппорт класс и сделать его более гибким, чтобы можно было передать драйвер либо была фабрика от модели и в итоге помимо фабричного метода мы избавимся от статики

```php
<?php

namespace MoonShine\Support;

use Illuminate\Database\Eloquent\Model;

final class DBOperators
{
    public function __construct(
        protected string $driver = 'mysql'
    ) {
    }

    public static function byModel(Model $model): self
    {
        $connection = $model->getConnectionName();

        return new self(
            config("database.connections.$connection.driver")
        );
    }

    public function like(): string
    {
        return match ($this->driver) {
            'pgsql' => 'ILIKE',
            default => 'LIKE',
        };
    }
}
```

2024-02-10 09:56 UTC, JeRabix commented
Оч красиво) Спасибо, сегодня внесу правку

2024-02-13 08:59 UTC, lee-to requested changes

2024-02-13 08:59 UTC, lee-to commented on src/Support/DbOperators.php
> +final class DbOperators
Давай назовем DBOperators

2024-02-13 08:59 UTC, lee-to commented on src/Support/DbOperators.php
> +        ?string $driver = 'mysql'
тогда здесь нужно по дефолту null

2024-02-13 09:24 UTC, JeRabix commented
Внёс корректировки

2024-02-13 10:23 UTC, merged