feat: Add heading gradation
moonshine-software/moonshine pull request #820
Opened 2024-02-22 11:00 UTC by AkostDev

Сейчас декорация `Heading::make()` "обёрнута" в тег _div_ и чтобы сделать нормальный заголовок нужно использовать метод `customAttributes()`. Да и смысл заголовка в том, чтобы он немного выделялся, поэтому добавил немного "сахара".

### Несколько примеров использования
#### Как сейчас
`Heading::make('Dashboard')`

#### Варианты с тегом _h1 - h4_
```
Heading::make('Dashboard')->h('1')
Heading::make('MoonShine')->h('2')
Heading::make('Demo version')->h(3)
Heading::make('Heading')->h('h4')
```

#### Варианты с тегом _div_ и классом _h1 - h4_
```
Heading::make('Dashboard')->h('1', false)
Heading::make('MoonShine')->h('2', false)
Heading::make('Demo version')->h(3, false)
Heading::make('Heading')->h('h4', false)
```

#### Варианты с тегом _p_ и классом _h1 - h4_
```
Heading::make('Dashboard')->tag('p')->h('1')
Heading::make('MoonShine')->tag('p')->h('2')
Heading::make('Demo version')->tag('p')->h(3)
Heading::make('Heading')->tag('p')->h('h4')
```

2024-02-22 12:39 UTC, lee-to commented
От себя скажу что выглядит не очень хорошей идеей глобально задвать hN стили, возможен конфликт с prose

2024-02-22 12:42 UTC, AkostDev commented
> От себя скажу что выглядит не очень хорошей идеей глобально задвать hN стили, возможен конфликт с prose

А если обернуть в свой контейнер
.heading > h1 ...

2024-02-22 15:07 UTC, DissNik commented
`Heading` это системный компонент, он используется на дефолтных страницах, а для кастома мне кажется проще использовать:
```
FlexibleRender::make('<h2>Title</h2>')
```
Или сделать свой blade компонент

2024-02-22 16:54 UTC, AkostDev commented
> `Heading` это системный компонент, он используется на дефолтных страницах

Я понимаю, но это реализация не должна сломать ничего)

> `FlexibleRender::make('<h2>Title</h2>')`

В случае с FlexibleRender всё равно стилей для заголовков нет никаких и это будет тот же Heading.

> Или сделать свой blade компонент

Как вариант, можно сделать отдельно декорацию со своим шаблоном, чисто для заголовков, но всё равно придётся оборачивать в свой контейнер, чтоб задать стили без конфликта с тэйлвиндовским prose.

2024-02-23 05:18 UTC, lee-to commented
Давай сеттер сделаем только int

2024-02-23 07:42 UTC, lee-to commented
Так ну и проверку на значение с минусом

2024-02-23 08:08 UTC, lee-to requested changes

2024-02-23 08:08 UTC, lee-to commented on src/Traits/WithTag.php
> +trait WithTag
Переименовать в HasDifferentHtmlTag

2024-02-23 08:08 UTC, lee-to commented on src/Traits/WithTag.php
> +}
На твое усмотрение но можно еще добавить флаг и метод указывающий что тег может не закрываться и иметь вид
<input />

2024-02-23 08:08 UTC, lee-to commented on src/Traits/WithHeadingGradation.php
> +                'gradation must be between 1 and 6'
С большой буквы

2024-02-23 08:19 UTC, AkostDev commented on src/Traits/WithHeadingGradation.php
> +                'gradation must be between 1 and 6'
> С большой буквы

Я за пример брал трейт WithColumnSpan (columnSpan), там название переменной имеется в виду.

2024-02-23 08:48 UTC, lee-to commented on src/Traits/WithHeadingGradation.php
> +                'gradation must be between 1 and 6'
> > С большой буквы
> 
> Я за пример брал трейт WithColumnSpan (columnSpan), там название переменной имеется в виду.

Просто твой трейт я думаю может еще где нибудь использовать в дальнейшем

2024-02-23 08:48 UTC, lee-to commented on src/Traits/WithHeadingGradation.php
> +                'gradation must be between 1 and 6'
> > С большой буквы
> 
> Я за пример брал трейт WithColumnSpan (columnSpan), там название переменной имеется в виду.

а я о другом))) ну пусть будет с мал

2024-02-23 13:22 UTC, AkostDev commented on src/Traits/WithTag.php
> +}
Думаю, сейчас оставлю так, но в бэклог добавить, что нужно развить этот трейт или даже отдельно сделать декоратор

2024-02-23 13:42 UTC, lee-to commented
@DissNik даешь добро?

2024-02-23 14:06 UTC, DissNik commented
Если будет желание, то можно в доку  добавить

2024-02-23 14:37 UTC, merged