fix: MakeUserCommand, add validation for email already exist
moonshine-software/moonshine pull request #821
Opened 2024-02-22 18:04 UTC by JeRabix

### Features
Добавил в команду создания пользователя валидацию на уникальность email'а
также required параметр накинул на все параметры

2024-02-23 05:49 UTC, DissNik requested changes

2024-02-23 05:49 UTC, DissNik commented on src/Commands/MakeUserCommand.php
> +
Зачем повторная валидация?

2024-02-23 05:49 UTC, DissNik commented on src/Commands/MakeUserCommand.php
>          if ($username && $name && $password) {
Раз все поля стали обязательными то условие не нужно

2024-02-23 06:30 UTC, JeRabix commented on src/Commands/MakeUserCommand.php
> +
Потому что могут email в аргумент команды сразу передать — username=test@mail.ru

2024-02-23 06:30 UTC, JeRabix commented on src/Commands/MakeUserCommand.php
>          if ($username && $name && $password) {
Да, поправлю

2024-02-23 09:43 UTC, JeRabix commented on src/Commands/MakeUserCommand.php
>          if ($username && $name && $password) {
![image](https://github.com/moonshine-software/moonshine/assets/46298617/f85c6442-f60a-4fbc-82b2-dbeb73f3d9e3)

@DissNik вот такой кейс еще есть

ничё страшного что name и password пустые строки в БД могут быть?

2024-02-23 13:15 UTC, lee-to requested changes

2024-02-23 13:15 UTC, lee-to commented on src/Commands/MakeUserCommand.php
> +        return $isAlreadyExist ? "User with email $email already exist" : null;
Странный метод который возвращает сразу текст ошибки) лучше вернуть bool а уже в процессе обработать

2024-02-23 13:15 UTC, lee-to commented on src/Commands/MakeUserCommand.php
> +        $emailError = $this->validateUserEmail($username);
Вместо двойной лучше принять как есть а потом сделать валидацию (убрать validate: )

2024-02-25 12:40 UTC, JeRabix commented on src/Commands/MakeUserCommand.php
> +        return $isAlreadyExist ? "User with email $email already exist" : null;
Ну тут 2 причины есть:

1 - Текст ошибки 2 раза прийдётся задублировать либо еще одну функцию делать, которая например по коду ошибки сматчит текст ошибки
2 - в дальнейшем валидация может быть не только на уникальность email'a, а также например можно в эту функцию добавить валидацию на то что email - валидный email и тд. и тогда прийдётся разбивать на отдельные функции это как-то

2024-02-25 12:44 UTC, JeRabix commented on src/Commands/MakeUserCommand.php
> +        $emailError = $this->validateUserEmail($username);
если мы уберём validate: - валидация будет при вводе существующего email'а - останавливать консольную команду - что будет не очень удобно, прийдёться перезапускать команду.

Сейчас же - laravel prompt - просто показывает ошибку и даёт сразу же исправить email дописам один символ.

Если смущает что происходит 2 запроса в БД дублирующих - могу как-то оптимизировать этот запрос, но это просто команда на создание пользователя, я не думаю что это критично.

Зато станет намного удобней при создании пользователя - не прийдёться перезапускать команду при ошибке.

2024-02-26 03:38 UTC, lee-to commented
Добрался до компа и взглянул нормально на pr и сразу понял что у нас username ведь не всегда email, проверка на валидный емейл тут быть не может, только уникальность, но если упадет ошибка уникальности разве это страшно для админки? все таки это интерфейс разраба а не клиента

2024-02-26 03:44 UTC, lee-to commented
но если хочется сделать проверку на уникальность то сделать можно в несколько строк перед добавлением

1) вынести ввод username в отдельный метод
2) сделай рекурсию, хотя бы просто while(true) если уникальный уходим из цикла если нет просим ввести

2024-02-26 05:43 UTC, JeRabix commented
> Collaborator

Ну вот поступила просьба от одного из разраба что так было бы удобней, чтобы оно эксепшеном не падало.
Не критично, но и двойная проверка тоже не критично)
Но так удобней будет.

2024-03-02 12:08 UTC, lee-to commented
я закрою пр и сделал просто проверку уникальности, для всего остального можно просто сделать свою команду

2024-03-02 12:08 UTC, closed without merging