feat: translate Choices messages
moonshine-software/moonshine pull request #941
Opened 2024-05-10 12:03 UTC by dragomano

Fixes #940 

Примеры:

![sshot-27](https://github.com/moonshine-software/moonshine/assets/229402/f13673c9-a4da-4f01-9d95-8415afdcaf92)
![sshot-26](https://github.com/moonshine-software/moonshine/assets/229402/fa084af3-e370-4c28-98ec-e546b6b2fa10)

2024-05-10 15:30 UTC, lee-to requested changes

2024-05-10 15:30 UTC, lee-to commented on src/Traits/WithComponentAttributes.php
> +        $this->customAttributes = array_merge($this->customAttributes, [
Так делать нельзя, этот ужас будет у всех полей а нам нужны только Select и BelongsTo

2024-05-10 15:46 UTC, dragomano commented on src/Traits/WithComponentAttributes.php
> +        $this->customAttributes = array_merge($this->customAttributes, [
Ещё для BelongsToMany. Можно сделать в виде трейта для этих полей. Название `HasTranslatedChoices` подойдет?

```php
<?php

declare(strict_types=1);

namespace MoonShine\Traits\Fields;

use Illuminate\View\ComponentAttributeBag;

trait HasTranslatedChoices
{
    public function attributes(): ComponentAttributeBag
    {
        $this->customAttributes = array_merge($this->customAttributes, [
            'data-loading-text' => __('moonshine::ui.loading'),
            'data-no-results-text' => __('moonshine::ui.choices.no_results'),
            'data-no-choices-text' => __('moonshine::ui.choices.no_choices'),
            'data-item-select-text' => __('moonshine::ui.choices.item_select'),
            'data-unique-item-text' => __('moonshine::ui.choices.unique_item'),
            'data-custom-add-item-text' => __('moonshine::ui.choices.custom_add_item'),
            'data-add-item-text' => __('moonshine::ui.choices.add_item'),
            'data-max-item-text' => trans_choice(
                'moonshine::ui.choices.max_item',
                $this->customAttributes['data-max-item-count'] ?? 0
            ),
        ]);

        return parent::attributes();
    }
}
```

2024-05-10 15:51 UTC, lee-to commented on src/Traits/WithComponentAttributes.php
> +        $this->customAttributes = array_merge($this->customAttributes, [
Нет это плохое решение, нужно через метод customAttributes там где это требуется, переопределять вот так криво нельзя

2024-05-10 15:52 UTC, lee-to commented
Не спешите и попробуйте сделать нормальное решение или я закрою pr и мы продолжим сами в рамках issue

2024-05-10 16:17 UTC, DissNik requested changes

2024-05-10 16:17 UTC, DissNik commented on src/Traits/WithComponentAttributes.php
> +        $this->customAttributes = array_merge($this->customAttributes, [
почему их сразу во вьюху не вставить?
https://github.com/moonshine-software/moonshine/blob/ad7cdf6174e5b592bafdf56df9105f3c60962fe7/resources/views/components/form/select.blade.php#L9

2024-05-10 16:17 UTC, DissNik commented on src/Traits/WithComponentAttributes.php
> +        $this->customAttributes = array_merge($this->customAttributes, [
только надо сделать так чтоб можно было через customAttributes их переопределить, вдруг потребуется в разных полях разный текст, или для одного поля чтоб вообще не было подсказки а для остальных осталось

2024-05-10 16:34 UTC, lee-to commented on src/Traits/WithComponentAttributes.php
> +        $this->customAttributes = array_merge($this->customAttributes, [
> почему их сразу во вьюху не вставить?
> 
> https://github.com/moonshine-software/moonshine/blob/ad7cdf6174e5b592bafdf56df9105f3c60962fe7/resources/views/components/form/select.blade.php#L9

Да думаю идеально, главное через merge

2024-05-11 05:21 UTC, DissNik commented
Все таки вынос перевода во вьюху тоже было не правильное предложение :(

Сейчас перевод у select работает, а вот у input с тегами нет. Размещать их еще и во вьюхе input плохая идея. 

Предлагаю обсудить вариант с локализацией choices-js при инициализации
https://github.com/moonshine-software/moonshine/blob/2.x/resources/js/alpine/select.js

2024-05-11 05:59 UTC, DissNik commented
https://github.com/moonshine-software/moonshine/blob/2.x/resources/views/layouts/shared/assets.blade.php используется y18n и переводы уже доступны в js

2024-05-11 13:50 UTC, dragomano commented
Пожалуй, это будет наилучшим вариантом. Обновлю код, как доберусь до компа

2024-05-15 15:26 UTC, lee-to commented
> Пожалуй, это будет наилучшим вариантом. Обновлю код, как доберусь до компа

Ждем)

2024-05-18 13:18 UTC, DissNik commented
🔥

2024-05-18 13:19 UTC, DissNik approved these changes

2024-05-19 12:22 UTC, lee-to commented
Спасибо! Отличная работа

2024-05-19 12:22 UTC, merged