feat: Add Markdown field
moonshine-software/moonshine pull request #968
Opened 2024-05-18 12:44 UTC by AkostDev

Issue #957

2024-05-18 17:17 UTC, DissNik requested changes

2024-05-18 17:17 UTC, DissNik commented on resources/css/components/easyMde.css
```
@import '../../../node_modules/easymde/dist/easymde.min.css';

.easyMde {
  @apply relative;

  & > textarea {
    @apply absolute !block w-full opacity-0;
    height: calc(100% - 34px);
  }

  .editor-toolbar {
    @apply rounded-t-md border border-b-0 border-gray-300 dark:border-dark-300 dark:bg-dark-800;

    button:hover {
      @apply border-gray-300 dark:border-dark-300 bg-transparent;
    }
    i.separator {
      @apply border-gray-300 dark:border-dark-300;
    }
  }

  .prose {
    @apply max-w-full bg-white p-4 dark:bg-dark-800;
  }

  .CodeMirror {
    @apply rounded-b-md border border-gray-300 dark:border-dark-300 dark:bg-dark-800;

    &-line {
      @apply dark:text-white;
    }
    &-cursor {
      @apply dark:border-white;
    }
  }
}
```

2024-05-18 17:21 UTC, DissNik commented on resources/css/components/easyMde.css
```
@apply relative;

& > textarea {
  @apply absolute !block w-full opacity-0;
  height: calc(100% - 34px);
}
```

решает проблему с получением фокуса, если поле обязательно для заполнения

2024-05-18 17:45 UTC, AkostDev commented on resources/css/components/easyMde.css
> ```
> @apply relative;
> 
> & > textarea {
>   @apply absolute !block w-full opacity-0;
>   height: calc(100% - 34px);
> }
> ```
> 
> решает проблему с получением фокуса, если поле обязательно для заполнения

Хорошее замечание!

2024-05-18 18:05 UTC, DissNik commented
но у меня все равно пока c required проблемы, нельзя отправить форму, хоть поле и заполнено

2024-05-18 19:21 UTC, lee-to commented
Насколько билд становится толще с этой либой? Может не стоит ее таскать всюду?

2024-05-18 19:22 UTC, lee-to commented
> но у меня все равно пока c required проблемы, нельзя отправить форму, хоть поле и заполнено

Может надо вызывать change ?

2024-05-19 03:33 UTC, DissNik commented
> > но у меня все равно пока c required проблемы, нельзя отправить форму, хоть поле и заполнено
> 
> Может надо вызывать change ?

forceSync: true нужно добавить

2024-05-19 03:59 UTC, DissNik commented on resources/js/alpine/easyMde.js
> +        element: this.$el,
```suggestion
        element: this.$el,
        forceSync: true,
        spellChecker: false,
```
Думаю стоит отключить проверку орфографии, эта библиотека тянет с cdn файлы.

2024-05-19 04:21 UTC, DissNik commented on resources/js/alpine/easyMde.js
> +    this.$nextTick(() => {
$nextTick() нужен?

2024-05-19 05:07 UTC, DissNik commented
<img width="195" alt="Снимок экрана 2024-05-19 в 10 03 01" src="https://github.com/moonshine-software/moonshine/assets/12373059/a3ad0fbb-3442-4141-86f7-c5c2dc8db7d4">
я бы это тоже убрал, но тогда нужно стили поправить немного для textarea

а еще можно добавить стили для поля при фокусе
```
.easyMde {
  @apply relative;

  &:has(.CodeMirror-focused) {
    &:before {
      @apply absolute top-0 rounded-md left-0 w-full ring ring-gray-200 ring-opacity-70 dark:ring-dark-100 dark:ring-opacity-30;
      height: calc(100% - 34px);
      content: '';
    }
  }
  ...
}
```

2024-05-19 12:21 UTC, lee-to commented on resources/js/alpine/easyMde.js
> +    this.$nextTick(() => {
Здесь нет x-id поэтому смысла не вижу

2024-05-19 17:09 UTC, AkostDev commented on resources/js/alpine/easyMde.js
> +        element: this.$el,
> Думаю стоит отключить проверку орфографии, эта библиотека тянет с cdn файлы.

Согласен отключить проверку орфографии, но сделать доступной её через параметр в будущем.

2024-05-19 17:12 UTC, AkostDev commented on resources/js/alpine/easyMde.js
> +    this.$nextTick(() => {
> Здесь нет x-id поэтому смысла не вижу

Да, не нужен. Артефакт остался, буду внимателней

2024-05-19 17:42 UTC, DissNik commented on resources/js/alpine/easyMde.js
> +        element: this.$el,
можно глянуть на реализацию https://github.com/moonshine-software/moonshine/blob/d124d170e45a9f5f99f6928053c7701a98ae2108/resources/js/alpine/tinymce.js#L37

если получится, вынести из tinymce и сделать более универсальным, в choicesjs это тоже можно будет использовать

2024-05-19 17:48 UTC, DissNik commented on resources/css/components/easyMde.css
> +    @apply absolute !block w-full opacity-0;
```suggestion
    @apply absolute !block w-full h-full opacity-0;
```

2024-05-19 17:53 UTC, AkostDev commented on resources/css/components/easyMde.css
> +    @apply absolute !block w-full opacity-0;
Вообще зачем его делать блочным, если плагин его скрывает?

2024-05-19 18:05 UTC, DissNik commented on resources/css/components/easyMde.css
> +    @apply absolute !block w-full opacity-0;
плагин его делает hidden, стилями мы его сделали видимым но с нулевой прозрачностью и расположили точно под полем, поэтому браузер может установить на нем фокус и вывести сообщение в нужном месте
<img width="689" alt="Снимок экрана 2024-05-19 в 23 01 14" src="https://github.com/moonshine-software/moonshine/assets/12373059/c8bb5850-0bcd-4ceb-9c3e-14253a563802">
 
Лучшего решения для required я не придумал. Если оставить скрытым, то в инспекторе будет ошибка, что не удалось установить фокус, а визуально никаких ошибок, но форма не отправится

2024-05-19 18:10 UTC, DissNik approved these changes

2024-05-20 07:40 UTC, AkostDev commented
> Насколько билд становится толще с этой либой? Может не стоит ее таскать всюду?

Да, билд в 2 раза тяжелей становится...
Вынесу в ассеты

2024-05-21 06:46 UTC, merged