feat: custom name for export file
moonshine-software/moonshine pull request #987
Opened 2024-05-24 07:27 UTC by khlystou

Добавил метод для указания пользовательского имени файла в ExportHandler

```
public function export(): ?ExportHandler
{
    return ExportHandler::make('Export')
        ->filename(sprintf('export_%s', date('Ymd-His')))
        ->dir('/exports')
        ->queue();
}
```

2024-05-24 08:06 UTC, lee-to requested changes

2024-05-24 08:06 UTC, lee-to commented on src/Handlers/ExportHandler.php
> +    public function createPath(): string
Давай переделаем на приватную и переименуем в generateFilePath

2024-05-24 21:08 UTC, khlystou commented
Сделано

2024-05-25 02:50 UTC, DissNik commented on src/Handlers/ExportHandler.php
> +        $path = Storage::disk($this->getDisk())->path($this->createPath());
```suggestion
        $path = Storage::disk($this->getDisk())->path($this->generateFilePath());
```

2024-05-26 07:57 UTC, merged